alias beers=mspdebug
alias ls="ls -lh --color"
alias betterdd="sudo dcfldd"
alias t="tar xf"
alias sl=ls

complete -W "$(echo $(grep '^ssh ' ~/.bash_history | sort -u | sed 's/^ssh //'))" ssh

function svn() {
	case $* in
		st ) shift 1; command svn status | sort -k 2 ;;
		up ) command svn --ignore-externals up ;;
		* ) command svn "$@" ;;
	esac
}

# Setup autojump
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && . ~/.autojump/etc/profile.d/autojump.sh

# Setup powerline-bash
function _update_ps1() {
	export PS1="$(~/git/powerline-bash/powerline-bash.py $? --width ${COLUMNS})"
}
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} _update_ps1"

function grepr() {
	command grep -rn --color $* ./*
}

export SVN_EDITOR=vim

